### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/infografia-de-hilos-IMA-G#2]
[HILOS EN C#.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-IMA-G/files/6459805/HILOS.EN.C.pdf)

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 19/20

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 19/20.

CALIFICÓ: RIGOBERTO RAMIREZ NICOLÁS

**Comment by josealfredo79** [comment]
Bien hecho y revisado
